version: '3.9'
services:
    db:
        image: postgres:15.3
        environment:
            POSTGRES_USER: laravel_products
            POSTGRES_PASSWORD: laravel_products!
        ports:
            - '127.0.0.1:5432:5432'
        volumes:
            - 'laravel-db:/var/lib/postgresql/data'
    fpm:
        container_name: 'product-management-example'
        build:
            context: .docker/php
            target: fpm
        volumes:
            - 'laravel-sync:/var/www/html:nocopy'
            - '.docker/php/php.ini:/usr/local/etc/php/php.ini'
            - '.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf'
        depends_on:
            - db
            - mailhog
    fpm_xdebug:
        build:
            context: .docker/php
            target: fpm-debug
        volumes:
            - 'laravel-sync:/var/www/html:nocopy'
            - '.docker/php/php.ini:/usr/local/etc/php/php.ini'
            - '.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf'
        environment:
            PHP_IDE_CONFIG: serverName=localhost
        depends_on:
            - fpm
    web:
        image: 'nginx:1.19'
        volumes:
            - 'laravel-sync:/var/www/html:nocopy'
            - '.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
            - '.docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
            - '.docker/nginx/ssl:/etc/nginx/ssl'
            - '.docker/nginx/40-ownership-folder.sh:/docker-entrypoint.d/40-ownership-folder.sh'
        ports:
            - '127.0.0.1:80:80'
            - '127.0.0.1:443:443'
        depends_on:
            fpm:
                condition: service_started
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '127.0.0.1:8025:8025'
volumes:
    laravel-db:
    laravel-sync:
